# Generated by Django 4.2.16 on 2024-11-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='books/', verbose_name='Загрузите картинку')),
                ('title', models.CharField(max_length=100, verbose_name='Напишите название книги')),
                ('description', models.TextField(default='Lorem Ipsum', verbose_name='Напишите описание книги')),
                ('price', models.FloatField(verbose_name='Укажите цену книги')),
                ('date_published', models.DateField(verbose_name='Укажите дату публикации книги')),
                ('genre', models.CharField(choices=[('Детектив', 'Детектив'), ('Роман', 'Роман'), ('Детские', 'Детские')], default='Детектив', max_length=100, verbose_name='Укажите жанр книги')),
                ('pages', models.CharField(max_length=50, verbose_name='Укажите количество страниц в книге')),
                ('author', models.CharField(max_length=30, verbose_name='Укажите автора книги')),
                ('audio_book', models.URLField(verbose_name='Укажите ссылку на аудио-книгу')),
            ],
        ),
    ]
