# Generated by Django 4.2.16 on 2024-11-12 15:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_books_genre_alter_books_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('description', models.TextField(verbose_name='Напишите отзыв о книге')),
                ('mark', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оцените книгу от 1 до 5')),
                ('review_books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_books', to='main_page.books')),
            ],
            options={
                'verbose_name': 'Отзыв к книге',
                'verbose_name_plural': 'Отзывы к книгам',
            },
        ),
    ]
