# Generated by Django 4.2.16 on 2024-11-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_reviewbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewbooks',
            name='description',
            field=models.TextField(null=True, verbose_name='Напишите отзыв о книге'),
        ),
    ]
